/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.xmlportletfactory.tnsoft.qrperson.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the person service. Represents a row in the &quot;qrperson_person&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.xmlportletfactory.tnsoft.qrperson.model.impl.personModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.xmlportletfactory.tnsoft.qrperson.model.impl.personImpl}.
 * </p>
 *
 * @author Jack A. Rider
 * @see person
 * @see org.xmlportletfactory.tnsoft.qrperson.model.impl.personImpl
 * @see org.xmlportletfactory.tnsoft.qrperson.model.impl.personModelImpl
 * @generated
 */
public interface personModel extends BaseModel<person>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a person model instance should use the {@link person} interface instead.
	 */

	/**
	 * Returns the primary key of this person.
	 *
	 * @return the primary key of this person
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this person.
	 *
	 * @param primaryKey the primary key of this person
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the kunde ID of this person.
	 *
	 * @return the kunde ID of this person
	 */
	public long getKundeId();

	/**
	 * Sets the kunde ID of this person.
	 *
	 * @param kundeId the kunde ID of this person
	 */
	public void setKundeId(long kundeId);

	/**
	 * Returns the company ID of this person.
	 *
	 * @return the company ID of this person
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this person.
	 *
	 * @param companyId the company ID of this person
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this person.
	 *
	 * @return the group ID of this person
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this person.
	 *
	 * @param groupId the group ID of this person
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this person.
	 *
	 * @return the user ID of this person
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this person.
	 *
	 * @param userId the user ID of this person
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this person.
	 *
	 * @return the user uuid of this person
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this person.
	 *
	 * @param userUuid the user uuid of this person
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this person.
	 *
	 * @return the user name of this person
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this person.
	 *
	 * @param userName the user name of this person
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this person.
	 *
	 * @return the create date of this person
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this person.
	 *
	 * @param createDate the create date of this person
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this person.
	 *
	 * @return the modified date of this person
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this person.
	 *
	 * @param modifiedDate the modified date of this person
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the firstname of this person.
	 *
	 * @return the firstname of this person
	 */
	@AutoEscape
	public String getFirstname();

	/**
	 * Sets the firstname of this person.
	 *
	 * @param Firstname the firstname of this person
	 */
	public void setFirstname(String Firstname);

	/**
	 * Returns the middlename of this person.
	 *
	 * @return the middlename of this person
	 */
	@AutoEscape
	public String getMiddlename();

	/**
	 * Sets the middlename of this person.
	 *
	 * @param Middlename the middlename of this person
	 */
	public void setMiddlename(String Middlename);

	/**
	 * Returns the lastname of this person.
	 *
	 * @return the lastname of this person
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this person.
	 *
	 * @param Lastname the lastname of this person
	 */
	public void setLastname(String Lastname);

	/**
	 * Returns the kunde description of this person.
	 *
	 * @return the kunde description of this person
	 */
	@AutoEscape
	public String getKundeDescription();

	/**
	 * Sets the kunde description of this person.
	 *
	 * @param kundeDescription the kunde description of this person
	 */
	public void setKundeDescription(String kundeDescription);

	/**
	 * Returns the user document of this person.
	 *
	 * @return the user document of this person
	 */
	public long getUserDocument();

	/**
	 * Sets the user document of this person.
	 *
	 * @param userDocument the user document of this person
	 */
	public void setUserDocument(long userDocument);

	/**
	 * Returns the city of this person.
	 *
	 * @return the city of this person
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this person.
	 *
	 * @param City the city of this person
	 */
	public void setCity(String City);

	/**
	 * Returns the user email of this person.
	 *
	 * @return the user email of this person
	 */
	@AutoEscape
	public String getUserEmail();

	/**
	 * Sets the user email of this person.
	 *
	 * @param userEmail the user email of this person
	 */
	public void setUserEmail(String userEmail);

	/**
	 * Returns the folder d l ID of this person.
	 *
	 * @return the folder d l ID of this person
	 */
	public long getFolderDLId();

	/**
	 * Sets the folder d l ID of this person.
	 *
	 * @param folderDLId the folder d l ID of this person
	 */
	public void setFolderDLId(long folderDLId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(person person);

	@Override
	public int hashCode();

	@Override
	public CacheModel<person> toCacheModel();

	@Override
	public person toEscapedModel();

	@Override
	public person toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}